# Generated by Django 5.0.2 on 2024-03-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='booking_id',
        ),
    ]
