# Generated by Django 5.0.2 on 2024-03-10 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_borrow_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='fine',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrowedOn',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='fineAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.book'),
        ),
    ]
