# Generated by Django 5.0.2 on 2024-03-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_rename_borrowedon_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='borrow_date',
            new_name='borrowed_on',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='fine',
        ),
        migrations.AddField(
            model_name='borrow',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.student'),
        ),
    ]
