# Generated by Django 5.0.2 on 2024-03-12 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_rename_borrow_date_borrow_borrowed_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False, unique=True)),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel.book')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel.student')),
            ],
        ),
    ]
